[HOTFIX] Add safety conditions for rendering Edit Funding Button
Users are intermittently getting this error:

```
TypeError: Cannot read property 'finalReward' of undefined
```

The bug could be occurring in special proposals where the Edit Funding button encounters rendering problems because there's no `proposalVersions` field for special proposals. This diff adds the safety condition so the button renders without problems.